🛠️ chore: CD 파이프라인 구축

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -15,18 +15,15 @@ permissions:
   contents: read
 
 jobs:
-  CI-CD:
+  build:
     runs-on: ubuntu-latest
     steps:
-    # JDK setting - github actions에서 사용할 JDK 설정 (aws 과 project의 java 버전과 별도로 관리)
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
     - name: Set up JDK 17
-      uses: actions/setup-java@v3
+      uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
-        
-    ## gradle caching (빌드 시간 줄이기)
     - name: Gradle Caching
       uses: actions/cache@v3
       with:
@@ -52,6 +49,12 @@ jobs:
     # gradle build
     - name: Build with Gradle
       run: ./gradlew clean build -x test
+
+    - name: docker build and registry push
+      run: |
+        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_LOGIN }} --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
+        docker build -t ${{ secrets.DOCKER_PRIVATE_REPO }}/grwm-server:latest .
+        docker push ${{ secrets.DOCKER_REPO }}/grwm-server:latest
 
     # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
     # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
@@ -82,3 +85,29 @@ jobs:
     # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
     - name: Generate and submit dependency graph
       uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
+
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: deploy k8s
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USERNAME }}
+          password: ${{ secrets.SERVER_PASSWORD }}
+          script: |
+            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ DOCKER_LOGIN }} --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
+            export NCLOUD_ACCESS_KEY=${{ secrets.NCLOUD_ACCESS_KEY }}
+            export NCLOUD_SECRET_KEY=${{ secrets.NCLOUD_SECRET_KEY }}
+            export NCLOUD_API_GW=https://ncloud.apigw.ntruss.com
+            export NCLOUD_PROFILE=project
+            export PATH=$PATH:$HOME/bin
+            kubectl --kubeconfig="/root/kubeconfig.yml" set image deployment/grwm-server-deployment grwm-server-deployment=grwm-registry.kr.ncr.ntruss.com/grwm-server:latest --record
+            if ! kubectl --kubeconfig="/root/kubeconfig.yml" rollout status deployment/grwm-server-deployment --timeout=60s; then
+              echo "Deployment failed, starting rollback..."
+              kubectl --kubeconfig="/root/kubeconfig.yml" rollout undo deployment/grwm-server-deployment
+              echo "Rollback completed."
+            else
+              echo "Deployment succeeded."
+            fi
